
const keyMirror = require('keymirror');

const constants = keyMirror({
  CITIZEN_AUNTENTICATION_EVENT: null,
  DRIVER_AUNTENTICATION_EVENT: null,
  CITIZEN_AUTH_SUCCESS_EVENT: null,
  DRIVER_AUTH_SUCCESS_EVENT: null,
  NEW_ALARM_EVENT: null,
  POSITION_CHANGE_EVENT: null,
  MISSION_ACCOMPLISHED_EVENT: null,
  CITIZEN_SOCKET_TYPE: null,
  DRIVER_SOCKET_TYPE: null,
  SOCKET_NOT_FOUND: null,
  ALARM_NOT_FOUND_EVENT: null,
  UNAUTHORIZED_MISSION_COMPLETION_EVENT: null,
  CITIZEN_FEEDBACK_EVENT: null,
  UNAUTHORIZED_FEEDBACK_EVENT: null,
  AMBULANCE_POSITION_CHANGE_EVENT: null,
  CITIZEN_POSITION_CHANGE_EVENT: null,
  FAKE_ALARM_EVENT: null,
  ACCOUNT_DEACTIVATED_EVENT: null,
  SUCCESSFUL_FAKE_ALARM_DECLARATION_EVENT: null,
  ACCEPTED_REQUEST_EVENT: null,
  OTHER_CITIZEN_SELECTION_EVENT: null,
  REJECTED_REQUEST_EVENT: null
});

module.exports = constants;
